#!/bin/sh

set -e

hostname=$1

scp ./config/dev.secret.exs ec2-user@$hostname:~
scp ./config/prod.secret.exs ec2-user@$hostname:~
ssh ec2-user@$hostname 'cd cdb && git pull && cd .. && echo "rootpass" | sudo -Sv && sh ~/cdb/deploy-remote.sh'